# These are supported funding model platforms

# GitHub Sponsors - Best for open-source projects
# github: [eugeneous]  # Add when you enable GitHub Sponsors

# Patreon - Good for ongoing support with tiers
# patreon: eugeneous  # Add if you want monthly supporters

# Ko-fi - One-time tips + memberships
# ko_fi: eugeneous  # Good for quick tips

# Buy Me a Coffee - Simple one-time donations
# buy_me_a_coffee: eugeneous  # Alternative to Ko-fi

# Custom links - Your actual products/services
custom: ['https://eugeneous.dev/pricing', 'https://myplace.eugeneous.com', 'https://eugeneous.dev', 'https://discord.gg/pixelprodigy']
